### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by saifrahmed** [1712n/yachay-public#2]
I'm trying to get this to run but cant figure out a set of working dependencies, could you share a list?

**Comment by alinapark** [comment]
Hey Saif, thank you for the question - we have just updated the wiki with the working dependencies. 

On our end the models worked with pytorch 1.7.1 on python 3.6, the rest can be found [here](https://github.com/1712n/yachay-public/tree/master/conf_geotagging_model#dependencies)
